drop table tbl_booking;

CREATE TABLE tbl_booking(
	BookingID number(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Customername VARCHAR(20),
	LicenseNo VARCHAR(20),
	VehicleMake VARCHAR(20),
	ProposedDate date
);

SELECT * FROM tbl_booking;